version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: fek 
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: users 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fek -d users"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-app-network

  flyway:
    image: flyway/flyway:9-alpine
    container_name: flyway
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql  # Папка с миграциями
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/users
      FLYWAY_USER: fek
      FLYWAY_PASSWORD: 1234
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: migrate
    networks:
      - my-app-network

  auth_service:
    image: fekk/auth_service
    container_name: auth_service
    expose:
      - "8080"
    depends_on:
      flyway:
        condition: service_completed_successfully
    networks:
      - my-app-network

networks:
  my-app-network:
    external: true
    name: my-app-network

volumes:
  postgres_data:
