#bind_addr = "192.168.1.221:8080"
bind_addr = "${BIND_ADDR}"
log_level = "$LOG_LEVEL"

[store]
database_url = "host=${DB_URL} port=${DB_PORT} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable"
